#!/bin/bash
# This file must be placed in the root directory of your CESM source code
# For example: '~/home/cesm1_0', referred to from here on as CESM_ROOT
#
# This script creates a new CESM case named 'CASENAME' 
# located in the CESM_ROOT/CASEROOT directory.
# It then configures, builds and runs the case.

echo "Creating new case..."
scripts/create_newcase -case CASENAME -res RESOLUTION -compset COMPSET -mach MACHINE

cd CASEROOT

ENVCONF
echo "Configuring case..."
configure -cleanall
configure -case


echo "Building case..."
CASENAME.MACHINE.clean_build
CASENAME.MACHINE.build

echo "Running simulation..."
CASENAME.MACHINE.run

echo "Run complete."